version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "17 6 * * *"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      tailitium-upstream-images:
        patterns:
          - "technitium/dns-server"
          - "tailscale/tailscale"
    commit-message:
      prefix: "deps(docker)"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "43 6 * * *"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "deps(actions)"
    labels:
      - "dependencies"
      - "github-actions"
